# Generated by Django 5.0.4 on 2026-03-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_App', '0002_asset_inventoryitem_rename_role_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('Available', 'Available'), ('Repair', 'Repair')], default='Pending', max_length=25),
        ),
    ]
