# Generated by Django 5.0.4 on 2026-04-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_App', '0003_alter_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('Available', 'Available'), ('Repair', 'Repair')], default='Available', max_length=25),
        ),
    ]
