# Generated by Django 5.0.4 on 2026-04-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_App', '0004_alter_asset_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
